language: php

php:
  - 5.4

before_script: composer.phar install --dev
script: ./vendor/bin/phake dev:tests

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.net#proem"

branches:
  only:
    - master
    - develop
