language: php

php:
  - 5.4

script: phpunit --configuration tests/phpunit.xml

notifications:
  irc:
    on_success: change
    on_failure: always
    - "irc.freenode.net#proem"

branches:
  only:
    - master
    - develop
