language: php

php:
  - 5.4
  - 5.5

matrix:
  allow_failures:
    - php: 5.5

before_script: composer --prefer-source --dev install
script: ./vendor/bin/phake dev:tests

notifications:
  irc:
    on_success: change
    on_failure: always
    channels:
      - "irc.freenode.net#proem"

branches:
  only:
    - master
    - develop
